### ISSUE TITLE
Undefined cpu.Stats

### ISSUE THREAD

**Issue by trinhdaiphuc** [livekit/protocol#272]
I'm using the library on Macbook M1 and get error

```
# github.com/livekit/protocol/utils
../../../go/pkg/mod/github.com/livekit/protocol@v1.3.1/utils/cpu_all.go:10:12: undefined: cpu.Stats
../../../go/pkg/mod/github.com/livekit/protocol@v1.3.1/utils/cpu_all.go:14:20: undefined: cpu.Get
../../../go/pkg/mod/github.com/livekit/protocol@v1.3.1/utils/cpu_all.go:25:19: undefined: cpu.Get
```

It looks like the library `github.com/mackerelio/go-osstat/cpu` is not support for Macbook M1

os: MacOS 12.6.2
golang: v1.19.4

**Comment by davidzhao** [comment]
@trinhdaiphuc which version are you using?

**Comment by davidzhao** [comment]
it does support M1 macbook. please ensure you ran a `go mod tidy` to pull in the dependencies

**Comment by trinhdaiphuc** [comment]
Hi @davidzhao, I have already run `go mod tidy` but it not works

**Comment by snakebenjm** [comment]
@trinhdaiphuc U need use cgo environment, like this 'CGO_ENABLED=1 go run cmd/server/main.go'
