### ISSUE TITLE
macOS Import Dependency Failure

### ISSUE THREAD

**Issue by GeekenDev** [livekit/protocol#659]
**Dependency**: https://github.com/mackerelio/go-osstat

**My machine**: Darwin amd64 - (MacOS - 14.2.1)
**Go Version**: (go1.22.1 darwin/amd64)

I did some digging and it states CPU support on darwin requires cgo. Is there anything special I need to be doing to source the necessary dependency?  Screenshots below. 
(*1: unavailable without cgo)

### My project that imports resources from this repo:

<img width="1113" alt="Screenshot 2024-03-14 at 2 23 59 PM" src="https://github.com/livekit/protocol/assets/5626645/3e39fb32-20d7-4156-81b3-ac56d6871027">

### The source file in question from this repo:
<img width="779" alt="Screenshot 2024-03-14 at 2 20 02 PM" src="https://github.com/livekit/protocol/assets/5626645/d109deb0-8517-4da7-9be4-2d2bb24a781b">

### The imports inside of my project:
<img width="765" alt="Screenshot 2024-03-14 at 2 23 01 PM" src="https://github.com/livekit/protocol/assets/5626645/a06e8b37-a2db-4880-a4ef-33a6e129971f">

**Comment by dennwc** [comment]
Hmm, right, this is not the first time it happens. We may need to move the CPU stats helpers to a separate package to avoid cgo requirement for the main protocol package.

**Comment by GeekenDev** [comment]
This has to be fastest response, commit, and PR i've ever seen. Gracias @dennwc 😎

**Comment by dennwc** [comment]
@GeekenDev You're welcome! Until we tag the next release update your `go.mod`:
```
github.com/livekit/protocol 4d22b4ce36d213847a65521e4a17bbd0ff56ffc8
```
Plus `go mod tidy` and it should do the trick. Let us know if there are other similar issues.
